### ISSUE TITLE
Build fails on resource_pipeline.go

### ISSUE THREAD

**Issue by NickLarsenNZ** [cathive/terraform-provider-concourse#3]
`go build` fails with the following error:

```
#  terraform-provider-concourse/concourse
concourse/resource_pipeline.go:34:55: not enough arguments in call to concourse.CreateOrUpdatePipelineConfig
	have (string, string, []byte)
	want (string, string, []byte, bool)
concourse/resource_pipeline.go:190:57: not enough arguments in call to concourse.CreateOrUpdatePipelineConfig
	have (string, string, []byte)
	want (string, string, []byte, bool)
...

Compilation finished with exit code 2
```

**Comment by NickLarsenNZ** [comment]
The extra `bool` on this line:
https://github.com/cathive/terraform-provider-concourse/blob/master/concourse/resource_pipeline.go#L190

Is for checkCredentials. Is this something that would be configurable by the user? Or should we hard set it to something?

**Comment by headcr4sh** [comment]
Not quite sure, yet.
I don't think, that a user might provide some sane input, here... therefore I would go with the automatically generated hard-coded approach for now.
